include: "rules/common.smk"

##### Target rules #####


rule all:
    input:
        config["ref_path"] + ".fai",
#        os.path.join(config["working_dir"], "sams/mapped/{sample}-{unit}.sam")
#        "results/annotated/all.vcf.gz",
#        "results/qc/multiqc.html",
#        "results/plots/depths.svg",
#        "results/plots/allele-freqs.svg",


##### Modules #####


include: "rules/ref.smk"
#include: "rules/mapping.smk"
#include: "rules/calling.smk"
#include: "rules/filtering.smk"
#include: "rules/stats.smk"
#include: "rules/qc.smk"
#include: "rules/annotation.smk"
