---
title: "HMM exploration"
author: "Ian Brettell"
date: '`r format(Sys.Date())`'
output:
  html_document:
    toc: true
    toc_float: true
    dev: 'svg'
    number_sections: true
    keep_md: false
    pandoc_args: --lua-filter=color-text.lua
    highlight: pygments
---

# Load libraries

```{r}
library(tidyverse)
library(ViteRbi)
```


# Read in test data

```{r}
test_file = "/hps/nobackup/birney/users/ian/somites/dpABs/batch_01/bwamem2/1.txt"

d = readr::read_tsv(test_file,
                    col_types = c("iicici"), 
                    col_names = F)
# Rename columns to make them consistent with Tom's code
colnames(d) = gsub("X", "V", colnames(d))

head(d)
```

# Bin all chrs and plot

```{r}
# `bin_all_chrs`

max_count = 15
bin_len = 5000

d_list = split(d, f = d$V1)

# Extract two chromosomes for testing
d_list = d_list[1:2]

head(d_list$`1`)

# Loop `bin_single` over each chromosome
binned_chrs = lapply(d_list, function(d){
  cleand = d[d$V4 < max_count & d$V6 < max_count,] # remove counts over `max_count`
  cleand$bin = floor(cleand$V2 / bin_len) # get bin
  cleand$ratio = cleand$V4 / (cleand$V4 + cleand$V6) # get ratio of Cab to Kaga
  binned = as.data.frame(tapply(cleand$V4,cleand$bin,sum)) # get total Cab counts within each bin
  binned$v6sum = tapply(cleand$V6,cleand$bin,sum) # get total Kaga counts within each bin
  binned$bin = tapply(cleand$bin,cleand$bin,unique) # add `bin` column
  colnames(binned) = c("mat", "pat", "bin") 
  binned$ratio = binned$mat / (binned$mat + binned$pat) # add `ratio` column
  return(binned)
})

head(binned_chrs$`1`)

# `bin_all_chrs_and_plot`
binned = binned_chrs
bdf = do.call(rbind, binned) # bind list of chromosomes into single DF
bdf$chr = unlist(strsplit(rownames(bdf), "\\."))[seq(1, nrow(bdf)*2, by=2)] # add `chr` column

head(bdf)

# `collect_chunked_data`
all_binned = bdf
d = data.frame("/hps/nobackup/birney/users/ian/somites/dpABs/batch_01/bwamem2/1.txt", all_binned)
all_binned = d
all_binned$ratio[is.na(all_binned$ratio)] = 0.5 # ratio = `NaN` where counts are 0 for both Cab and Kaga. Replace with 0.5.
input = data.frame(1, all_binned$bin, all_binned$ratio)
```

## Run `ViteRbi`
```{r}
v = ViteRbi(input, active=F) # run ViteRbi

# Step-by-step

## Add data
data = input

## Add arguments
states = c(-1, 0, 1)
normalstate = 1
emiss = c(-1, 1, 0, 1, 1, 1)
trans = c(0.99, 0.01, 0, 0.005, 0.99, 0.005, 0, 0.01, 0.99)
ep = 2
tp = 3

jumpy = NULL

normalstates = vector()
u = unique(data[, 1]) # get unique values of first column (always going to be 1 because it was set in last line of previous chunk)
## The function then loops over `u`, but as there is only one value, we'll just show the guts of the loop
x = length(u)
d = data[data[, 1] == u[x], ]
## Run C funtion
res <- .C("ViteRbi", data = as.double(d[, 3]), states = as.double(rep(normalstate, 
    length(d[, 1]))), emissions = as.double(emiss), transitions = as.double(trans), 
    dN = as.integer(length(d[, 3])), sN = as.integer(length(states)), 
    eN = as.integer(ep), tN = as.integer(tp), PACKAGE = "ViteRbi")

# Finish `collect_chunked_data` function
all_binned$state = v[,4] # add ViteRbi output as `state` column
```

## Finish with remaining `run_rc_block.R` script

```{r}
bin1 = all_binned
colnames(bin1)[1] = "sample"

head(bin1)
```

