# Process phenotypes file for Ewan

## Get variables

```{r}
GENO_FILE = "/nfs/research/birney/users/ian/somites/association_testing/20211109_true/no_repeat_reads/inputs/20000.rds"
PHENO_FILE = here::here("data/20210917_First400_F2_DF.xlsx")
SOURCE_FILE = here::here("workflow/scripts/run_gwls_source.R")
BIN_LENGTH = 20000
OUT_FILE = here::here("data/20210917_First400_F2_DF_processed.txt")
TARGET_PHENOS = c("intercept", "mean")
```

## Get GWAS functions

```{r}
source(SOURCE_FILE)
```

## Load genotypes and positions

```{r}
in_list = readRDS(GENO_FILE)
```

## Read in phenotypes

```{r}
## Read in file and wrangle
phenos = readxl::read_xlsx(PHENO_FILE) %>%
    # adjust sample names
    dplyr::mutate(SAMPLE = fish %>% stringr::str_remove("KC")) %>%
    # select key columns
    dplyr::select(SAMPLE, all_of(TARGET_PHENOS)) %>%
    # ensure that the phenotype column is numeric
    dplyr::mutate(dplyr::across(all_of(TARGET_PHENOS),
                                ~ as.numeric(.x)))

## Filter genotypes for those that have phenotypes
in_list[["genotypes"]] = in_list[["genotypes"]] %>%
    dplyr::filter(in_list[["sample_order"]] %in% phenos$SAMPLE)

## Filter and order phenotypes
in_list[["phenotypes"]] = phenos %>%
    # filter phenotypes for those with genotypes
    dplyr::filter(SAMPLE %in% in_list[["sample_order"]]) %>%
    # join to `sample_order` to ensure phenotypes are in the correct order   
    dplyr::left_join(tibble::tibble(SAMPLE = in_list[["sample_order"]]),
                     .,
                     by = "SAMPLE")
```

## Save to file

```{r}
readr::write_tsv(in_list[["phenotypes"]],
                 OUT_FILE)
```

