# Annotations of GWAS hits

```{r}
library(here)
library(tidyverse)
library(biomaRt)
```

```{r}
DATE_OF_ASSOC_TEST = "20220214"
SITE_FILTER = "all_sites"
COVARIATES = "None"
INVERSE_NORM = "TRUE"
BIN_LENGTH = 5000
OUT_DIR = here::here("data", DATE_OF_ASSOC_TEST, "annotations")
```

## Intercept

```{r}
TARGET_PHENO = "intercept"
```

### Read in data

```{r}
GWAS_RESULTS = file.path("/hps/nobackup/birney/users/ian/somites/association_testing",
                         DATE_OF_ASSOC_TEST,
                         SITE_FILTER,
                         "true_results",
                         TARGET_PHENO,
                         COVARIATES,
                         INVERSE_NORM,
                         paste(BIN_LENGTH, ".rds", sep = ""))

RESULTS = readRDS(GWAS_RESULTS)

PERMS_PATHS = file.path("/hps/nobackup/birney/users/ian/somites/association_testing/",
                          DATE_OF_ASSOC_TEST,
                          SITE_FILTER,
                          "permutations",
                          TARGET_PHENO,
                          COVARIATES,
                          INVERSE_NORM,
                          BIN_LENGTH)
PERMS = list.files(PERMS_PATHS, full.names = T)
names(PERMS) = PERMS %>% 
  basename %>% 
  stringr::str_remove(".rds")

if ("p_value_REML" %in% colnames(RESULTS$results)){
  P_COL = "p_value_REML"
} else {
  P_COL = "p_value_REML.1"
}

# Rename column in results

if (P_COL == "p_value_REML.1"){
  RESULTS$results = RESULTS$results %>% 
    dplyr::rename(p_value_REML = p_value_REML.1)
}

# Read in permutation results and get `SIG_LEVEL`

PERM_LIST = purrr::map(PERMS, function(PERM){
  readRDS(PERM)
})

perm_df = purrr::map_dfr(PERM_LIST, function(PERM){
  OUT = tibble::tibble(MIN_P = PERM$results %>% 
                         dplyr::select(dplyr::all_of(P_COL)) %>%
                         min(., na.rm = T)
  )
}, .id = "SEED")

# Get minimum
SIG_LEVEL = min(perm_df$MIN_P)
```

### Pull significant loci

```{r}
SIG_LOCS = RESULTS$results %>% 
  dplyr::filter(p_value_REML < SIG_LEVEL) %>% 
  dplyr::select(CHROM = Chr,
                BIN_START = pos) %>% 
  dplyr::mutate(BIN_END = BIN_START + BIN_LENGTH - 1)
                
```


### Get annotations

```{r}
## Select dataset
olat_mart = biomaRt::useEnsembl(biomart = "ensembl", dataset = "olatipes_gene_ensembl")

olat_attr = biomaRt::listAttributes(olat_mart)

olat_genes = biomaRt::getBM(attributes = c("chromosome_name",
                                           "start_position",
                                           "end_position",
                                           "ensembl_gene_id",
                                           "hgnc_symbol",
                                           "ensembl_exon_id",
                                           "description",
                                           "strand",
                                           "transcript_start",
                                           "transcript_end"),
                             mart = olat_mart) 

olat_genes_r = olat_genes %>% 
  # change strand characters
  dplyr::mutate(strand = dplyr::recode(.$strand,
                                       `1` = "+",
                                       `-1` = "-")
                ) %>% 
  GenomicRanges::makeGRangesFromDataFrame(seqnames.field = "chromosome_name",
                                            start.field = "start_position",
                                            end.field = "end_position")

# convert hits to genomic ranges
sig_loc_r = SIG_LOCS %>% 
  GenomicRanges::makeGRangesFromDataFrame(seqnames.field = "CHROM",
                                          start.field = "BIN_START",
                                          end.field = "BIN_END",
                                          ignore.strand = T)


# find overlaps
olaps = GenomicRanges::findOverlaps(sig_loc_r, olat_genes_r)

# Pull out data frame of hits
hits = olat_genes[unique(olaps@to), ]

hits %>% 
  DT::datatable(.)
```

```{r}
# Save to file
readr::write_csv(hits,
                 file.path(OUT_DIR, paste(TARGET_PHENO, ".csv", sep = "")))
```

## PSM area

```{r}
TARGET_PHENO = "unsegmented_psm_area"
```

### Read in data

```{r}
GWAS_RESULTS = file.path("/hps/nobackup/birney/users/ian/somites/association_testing",
                         DATE_OF_ASSOC_TEST,
                         SITE_FILTER,
                         "true_results",
                         TARGET_PHENO,
                         COVARIATES,
                         INVERSE_NORM,
                         paste(BIN_LENGTH, ".rds", sep = ""))

RESULTS = readRDS(GWAS_RESULTS)

PERMS_PATHS = file.path("/hps/nobackup/birney/users/ian/somites/association_testing/",
                          DATE_OF_ASSOC_TEST,
                          SITE_FILTER,
                          "permutations",
                          TARGET_PHENO,
                          COVARIATES,
                          INVERSE_NORM,
                          BIN_LENGTH)
PERMS = list.files(PERMS_PATHS, full.names = T)
names(PERMS) = PERMS %>% 
  basename %>% 
  stringr::str_remove(".rds")

if ("p_value_REML" %in% colnames(RESULTS$results)){
  P_COL = "p_value_REML"
} else {
  P_COL = "p_value_REML.1"
}

# Rename column in results

if (P_COL == "p_value_REML.1"){
  RESULTS$results = RESULTS$results %>% 
    dplyr::rename(p_value_REML = p_value_REML.1)
}

# Read in permutation results and get `SIG_LEVEL`

PERM_LIST = purrr::map(PERMS, function(PERM){
  readRDS(PERM)
})

perm_df = purrr::map_dfr(PERM_LIST, function(PERM){
  OUT = tibble::tibble(MIN_P = PERM$results %>% 
                         dplyr::select(dplyr::all_of(P_COL)) %>%
                         min(., na.rm = T)
  )
}, .id = "SEED")

# Get minimum
SIG_LEVEL = min(perm_df$MIN_P)
```

### Pull significant loci

```{r}
SIG_LOCS = RESULTS$results %>% 
  dplyr::filter(p_value_REML < SIG_LEVEL) %>% 
  dplyr::select(CHROM = Chr,
                BIN_START = pos) %>% 
  dplyr::mutate(BIN_END = BIN_START + BIN_LENGTH - 1)
                
```


### Get annotations

```{r}
## Select dataset
olat_mart = biomaRt::useEnsembl(biomart = "ensembl", dataset = "olatipes_gene_ensembl")

olat_attr = biomaRt::listAttributes(olat_mart)

olat_genes = biomaRt::getBM(attributes = c("chromosome_name",
                                           "start_position",
                                           "end_position",
                                           "ensembl_gene_id",
                                           "hgnc_symbol",
                                           "ensembl_exon_id",
                                           "description",
                                           "strand",
                                           "transcript_start",
                                           "transcript_end"),
                             mart = olat_mart) 

olat_genes_r = olat_genes %>% 
  # change strand characters
  dplyr::mutate(strand = dplyr::recode(.$strand,
                                       `1` = "+",
                                       `-1` = "-")
                ) %>% 
  GenomicRanges::makeGRangesFromDataFrame(seqnames.field = "chromosome_name",
                                            start.field = "start_position",
                                            end.field = "end_position")

# convert hits to genomic ranges
sig_loc_r = SIG_LOCS %>% 
  GenomicRanges::makeGRangesFromDataFrame(seqnames.field = "CHROM",
                                          start.field = "BIN_START",
                                          end.field = "BIN_END",
                                          ignore.strand = T)


# find overlaps
olaps = GenomicRanges::findOverlaps(sig_loc_r, olat_genes_r)

# Pull out data frame of hits
hits = olat_genes[unique(olaps@to), ]

hits %>% 
  DT::datatable(.)
```

```{r}
# Save to file
readr::write_csv(hits,
                 file.path(OUT_DIR, paste(TARGET_PHENO, ".csv", sep = "")))
```

