# Exploration of GWLS hits

```{r, message = F, warning = F}
library(here)
source(here::here("book/source/04-Association_testing.R"))
```

## Read in data

### Get variables
```{r}
DATE_OF_ASSOC_TEST = 20220214

TARGET_PHENOS = c("unsegmented_psm_area")
names(TARGET_PHENOS) = TARGET_PHENOS

BIN_LENGTHS = c(5000)
names(BIN_LENGTHS) = BIN_LENGTHS

FILTERS = c("all_sites",
           "no_repeat_reads_or_pers_hets_filtered_for_read_count_and_cab_prop")
names(FILTERS) = FILTERS

PERMS_FILE = here::here("data", paste(DATE_OF_ASSOC_TEST, "_permutation_mins.csv", sep = ""))

PLOT_DIR = here::here("book/plots", DATE_OF_ASSOC_TEST, "hits_exploration")

```

### Read in files

```{r}
gwas_true = purrr::map(TARGET_PHENOS, function(PHENO){
  purrr::map(FILTERS, function(FILTER){
    # Get path to results directory
    RESULTS_DIR = file.path("/nfs/research/birney/users/ian/somites/association_testing", DATE_OF_ASSOC_TEST, FILTER, "true_results")
    # Read in results for each bin length
    purrr::map(BIN_LENGTHS, function(BIN_LENGTH){
      readRDS(file.path(RESULTS_DIR, PHENO, paste(BIN_LENGTH, ".rds", sep = "")))
    })
  })

})
```

#### Manhattans

Process data
```{r}
plot_dat = purrr::map(TARGET_PHENOS, function(PHENO){
  purrr::map(FILTERS, function(FILTER){
    purrr::map(BIN_LENGTHS, function(BIN_LENGTH){
      # clean GWAS results for plotting
      clean_gwas_res(gwas_true[[PHENO]][[FILTER]][[as.character(BIN_LENGTH)]],
                     bin_length = BIN_LENGTH,
                     chr_lens = med_chr_lens)
    })
  })

})

```

Read in significance levels from permutations

```{r}
perms_df_mins = readr::read_csv(PERMS_FILE,
                                col_types = c("ccid"))
```

```{r}
# Get palette


lapply(TARGET_PHENOS, function(PHENO){
  lapply(FILTERS, function(FILTER){
    lapply(BIN_LENGTHS, function(BIN_L){
      # Get significance level
      SIG_LEVEL = perms_df_mins %>% 
        dplyr::filter(TARGET_PHENO == PHENO,
                      SITE_FILTER == FILTER,
                      BIN_LENGTH == BIN_L) %>% 
        dplyr::pull(MIN_P)
      # Get palette
      pal = eval(as.name(paste(PHENO, "pal", sep = "_")))
      # Get target chromosome
      TARGET_CHROM = 3
      # Get chrom lenghts and breaks
      CHROM_END = med_chr_lens %>% 
        dplyr::filter(chr == TARGET_CHROM) %>% 
        dplyr::pull(end)
      X_BREAKS = seq(from = 0, to = CHROM_END, by = 5e6)
      # Plot
      df = plot_dat[[PHENO]][[FILTER]][[as.character(BIN_L)]] %>%
        # filter for target chromosome
        dplyr::filter(CHROM == TARGET_CHROM) %>% 
        # create `COLOUR` vector
        dplyr::mutate(COLOUR = dplyr::case_when(p_value_REML < SIG_LEVEL ~ pal[1],
                                                gtools::even(CHROM) ~ pal[2],
                                                gtools::odd(CHROM) ~ pal[3])) %>% 
        dplyr::mutate(CHROM = factor(CHROM, levels = med_chr_lens$chr)) 
      
      out_plot = df %>% 
        ggplot(aes(x = BIN_START,
                   y = -log10(p_value_REML),
                   label = BIN_START,
                   label2 = BIN_END)) + 
        geom_point(colour = df$COLOUR,
                   size = 0.5,
                   alpha = 0.5) +
        scale_x_continuous(breaks = X_BREAKS,
                           labels = X_BREAKS / 1e6) +
        theme_bw() +
        theme(panel.grid.major.x = element_blank(),
              panel.grid.minor.x = element_blank()
        ) +
        guides(colour = "none") +
        ggtitle(paste("Site filter: ", FILTER, "\nPhenotype: ", PHENO, "\nBin length: ",  BIN_L, sep = "")) +
        xlab("Mb") +
        ylab("-log10(p-value)") + 
        geom_hline(yintercept = -log10(SIG_LEVEL), colour = "#60D394", linetype = "dashed")
      
      out_plot
      
      # create output directory
      OUT_DIR = here::here(PLOT_DIR, PHENO, FILTER, BIN_L)
      dir.create(OUT_DIR, recursive = T, showWarnings = F)
      
      ggsave(file.path(OUT_DIR, paste(TARGET_CHROM, ".png", sep = "")),
       out_plot,
       device = "png",
       width = 9.6,
       height = 6,
       units = "in",
       dpi = 400)
    })
  })
})

out_plot = plot_man(out_clean,
                    site_filter = "all_sites",
                    phenotype = TARGET_PHENO,
                    bin_length = BIN_LENGTH, 
                    gwas_pal = intercept_pal,
                    med_chr_lens = med_chr_lens,
                    sig_level = SIG_LEVEL) +
                 ylim(0,7) + 
                 labs(subtitle = paste("Microscope: ", MICROSCOPE, "\nn samples: ", N_SAMPLES, sep = ""))

out_plot
```


